[package]
name = "vuv-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
anyhow = "1.0.80"
dirs = "5.0.1"
which = "6.0.0"
home = "0.5.9"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
